name: WakaTime status update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-readme:
    name: Update WakaTime Activity
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "master"
          COMMIT_MSG: "docs(wakatime): update code activity ðŸ‘½"
  rename-stats:
    name: Rename WakaTime Stats File
    needs: update-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Repo Changes
        run: git pull --rebase
      - name: Rename file
        run: mv ./images/stat.svg ./images/wakatime-stats.svg
      - name: Commit report
        run: |
          git stage "images/wakatime-stats.svg"
          git config --global user.name 'Ademola Adedeji'
          git config --global user.email 'iammola@users.noreply.github.com'
          git commit -am "docs(wakatime): rename stats file ðŸ‘½"
          git push
